export let _menus = [{
    "menuId": 101,
    "name": "菜单",
    "parentId": null,
    "status": "1"
}, {
    "menuId": 102,
    "parentId": null,
    "name": "菜单",
    "icon": null,
    "link": "http://github.com/github-web/",
    "status": "1",    
    "isParent": true
}, {
    "menuId": 103,
    "parentId": null,
    "name": "菜单",
    "icon": null,
    "link": "http://github.com/",
    "status": "1",
    "isParent": true
}, {
    "menuId": 104,
    "parentId": null,
    "name": "菜单",
    "icon": null,
    "link": "http://github.com/github-web/",
    "status": "1",    
    "isParent": true
}, {
    "menuId": 105,
    "parentId": null,
    "name": "菜单",
    "icon": null,
    "link": "http://github.com/",
    "status": "1",
    "isParent": false
}]